[tool.poetry]
name = "arc-flask-new"
version = "0.1.0"
description = ""
authors = ["zeefeerkee"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
